spring.application.name=back_software

spring.datasource.url=jdbc:postgresql://localhost:5432/software_madurez
spring.datasource.username=postgres
spring.datasource.password=72647986

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=98765432198765432198765432198765
jwt.expiration=86400000