spring.application.name=back_software

# Base de datos (obtenida dinámicamente desde la nube)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/software_madurez}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:72647986}

# JPA / Hibernate (Desactivamos 'create-drop' para no borrar la BD en producción)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=false

# Puerto dinámico asignado por la plataforma en la nube (Render, Railway, etc.)
server.port=${PORT:8080}

# ===============================
# JWT (Firma del Token)
# ===============================
jwt.secret=${JWT_SECRET:98765432198765432198765432198765}
jwt.expiration=${JWT_EXPIRATION:86400000}
